// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webappcaixapizzaria.Configuracao;

namespace webappcaixapizzaria.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webappcaixapizzaria.Model.Caixacontrole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datahoraabertura")
                        .HasColumnType("datetime2")
                        .HasColumnName("Datahoraabertura");

                    b.Property<int>("Datahorafechamento")
                        .HasColumnType("int")
                        .HasColumnName("Datahorafechamento");

                    b.Property<int>("Idfuncionario")
                        .HasColumnType("int")
                        .HasColumnName("Idfuncionario");

                    b.Property<int>("Valorfinalcaixa")
                        .HasColumnType("int")
                        .HasColumnName("Valorfinalcaixa");

                    b.Property<double>("Valorfundocaixa")
                        .HasColumnType("float")
                        .HasColumnName("Valorfundocaixa");

                    b.HasKey("Id");

                    b.ToTable("Caixacontrole");
                });

            modelBuilder.Entity("webappcaixapizzaria.Model.Caixalancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datahora")
                        .HasColumnType("datetime2")
                        .HasColumnName("Datahora");

                    b.Property<int>("Idcaixacontrole")
                        .HasColumnType("int")
                        .HasColumnName("Idcaixacontrole");

                    b.Property<int>("Idformapagamento")
                        .HasColumnType("int")
                        .HasColumnName("Idformapagamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacao");

                    b.Property<string>("Tipolancamento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipolancamento");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.ToTable("Caixalancamento");
                });

            modelBuilder.Entity("webappcaixapizzaria.Model.Formapagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Formapagamento");
                });

            modelBuilder.Entity("webappcaixapizzaria.Model.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fun_chapeira")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fun_chapeira");

                    b.Property<string>("Fun_login")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fun_login");

                    b.Property<string>("Fun_nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fun_nome");

                    b.Property<string>("Fun_senha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fun_senha");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
